services:
  webpage:
    build: .
    ports:
      - "8443:8443"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_HOSTNAME: ${SERVER_HOSTNAME}
      SERVER_SSL_ENABLED: ${SERVER_SSL_ENABLED}
      SERVER_SSL_KEY_STORE: ${SERVER_SSL_KEY_STORE}
      SERVER_SSL_KEY_STORE_TYPE: ${SERVER_SSL_KEY_STORE_TYPE}
      SERVER_SSL_KEY_ALIAS: ${SERVER_SSL_KEY_ALIAS}
      SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}

      DATABASE_JDBC_URL: ${DATABASE_JDBC_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      
      SISBUR_JDBC_URL: ${SISBUR_JDBC_URL}
      SISBUR_USERNAME: ${SISBUR_USERNAME}
      SISBUR_PASSWORD: ${SISBUR_PASSWORD}
      
      SISFISCAL_JDBC_URL: ${SISFISCAL_JDBC_URL}
      SISFISCAL_USERNAME: ${SISFISCAL_USERNAME}
      SISFISCAL_PASSWORD: ${SISFISCAL_PASSWORD}
    networks:
      - network_webpage

networks:
  network_webpage:
    external: true
